### ISSUE TITLE
catkin_make error 

### ISSUE THREAD

**Issue by ghost** [Mayankm96/airsim_img_publisher#1]
i get a long list of errors when running catkin_make first error is this,

ps i followed all the instructions ,

/home/yuthika/air_ws/src/airsim_img_publisher/src/airsim_img_publisher/AirSimClientWrapper.cpp: In member function ‘void AirSimClientWrapper::poll_frame(int)’:
/home/yuthika/air_ws/src/airsim_img_publisher/src/airsim_img_publisher/AirSimClientWrapper.cpp:70:37: **error: no matching function for call to** ‘msr::airlib::ImageCaptureBase::ImageRequest::ImageRequest(int&, msr::airlib::ImageCaptureBase::ImageType)’
   ImageReq(cameraId, ImageTyp::Scene),

**Comment by Mayankm96** [comment]
The issue is mostly due to the fact that the AirSim repository has changed a lot over time and my code has not been updated. Unfortunately, I do not have the time to look into the build errors right now. If you are able to fix it, it would be great to receive a PR on it. :)

**Comment by ghost** [comment]
i will try to look into it,  :) , have to go through the code anyway to get the get to the bottom.
